# config file version
apiVersion: 1

datasources:
  # <string, required> name of the datasource. Required
  - name: InfluxDB
    # <string, required> datasource type. Required
    type: influxdb
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <string> url
    url: http://${INFLUXDB_IP}:8086
    # This database should be mapped to a bucket
    database: telegraf
    # <map> fields that will be converted to json and stored in json_data
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    # <string> json object of data that will be encrypted
    secureJsonData:
      httpHeaderValue1: 'Token ${INFLUXDB_TOKEN}'
    # <bool> allow users to edit datasources from the UI.
    editable: true